Somnambulist\ValueObjects\Types\Geography\Country:
    type: embeddable

    fields:
        name:
            type: string
            length: 100

        code:
            type: Somnambulist\ValueObjects\Types\Geography\CountryCode
