Somnambulist\ValueObjects\Types\Measure\Distance:
    type: embeddable

    fields:
        value:
            type: decimal
            precision: 14
            scale: 3
            options:
                default: 0.0

        unit:
            type: Somnambulist\ValueObjects\Types\Measure\DistanceUnit
